"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabaseClient";

type Leader={id?:string;name:string;role:string;bio:string;photo_url:string;sort_order:number;published:boolean};
type Content={id?:string;section:string;title:string;body:string;metric_value:string;metric_label:string;document_url:string;document_name:string;sort_order:number;published:boolean};
const blankLeader=():Leader=>({name:"",role:"",bio:"",photo_url:"",sort_order:0,published:true});
const blankContent=():Content=>({section:"identity",title:"",body:"",metric_value:"",metric_label:"",document_url:"",document_name:"",sort_order:0,published:true});
export default function AdminPage(){
 const client=supabase; const [session,setSession]=useState<any>(null); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [status,setStatus]=useState("");
 const [leaders,setLeaders]=useState<Leader[]>([]),[contents,setContents]=useState<Content[]>([]),[gallery,setGallery]=useState<any[]>([]);
 const [leader,setLeader]=useState(blankLeader()),[leaderFile,setLeaderFile]=useState<File|null>(null),[editingLeader,setEditingLeader]=useState<string|null>(null);
 const [content,setContent]=useState(blankContent()),[docFile,setDocFile]=useState<File|null>(null),[editingContent,setEditingContent]=useState<string|null>(null);
 const [media,setMedia]=useState<File|null>(null),[mediaTitle,setMediaTitle]=useState(""),[mediaDescription,setMediaDescription]=useState("");
 useEffect(()=>{if(!client)return;client.auth.getSession().then(({data})=>setSession(data.session));const {data}=client.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[client]);
 useEffect(()=>{if(session)load()},[session]);
 async function load(){if(!client)return;const [l,c,g]=await Promise.all([client.from("organization_leaders").select("*").order("sort_order"),client.from("organization_content").select("*").order("sort_order"),client.from("gallery_items").select("*").order("created_at",{ascending:false})]);setLeaders(l.data||[]);setContents(c.data||[]);setGallery(g.data||[])}
 async function signIn(e:React.FormEvent){e.preventDefault();if(!client){setStatus("Supabase is not configured.");return;}setStatus("Signing in…");const {data,error}=await client.auth.signInWithPassword({email,password});if(error)setStatus(error.message);else{setSession(data.session);setStatus("Signed in.")}}
 async function saveLeader(e:React.FormEvent){e.preventDefault();if(!client){setStatus("Supabase is not configured.");return;}setStatus("Saving leader…");let url=leader.photo_url;if(leaderFile){const path=`leaders/${Date.now()}-${leaderFile.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const up=await client.storage.from("organization-media").upload(path,leaderFile,{upsert:true});if(up.error)return setStatus(up.error.message);url=client.storage.from("organization-media").getPublicUrl(path).data.publicUrl}if(!leader.name||!leader.role||!url)return setStatus("Name, role and photo are required.");const payload={...leader,photo_url:url};const r=editingLeader?await client.from("organization_leaders").update(payload).eq("id",editingLeader):await client.from("organization_leaders").insert(payload);if(r.error)return setStatus(r.error.message);setStatus(editingLeader?"Leader updated.":"Leader added.");setLeader(blankLeader());setLeaderFile(null);setEditingLeader(null);load()}
 async function saveContent(e:React.FormEvent){e.preventDefault();if(!client){setStatus("Supabase is not configured.");return;}setStatus("Saving information…");if(!content.title)return setStatus("Title is required.");let payload:any={...content};if(docFile){const path=`documents/${Date.now()}-${docFile.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const up=await client.storage.from("organization-documents").upload(path,docFile,{upsert:true});if(up.error)return setStatus(up.error.message);payload.document_url=client.storage.from("organization-documents").getPublicUrl(path).data.publicUrl;payload.document_name=docFile.name}const r=editingContent?await client.from("organization_content").update(payload).eq("id",editingContent):await client.from("organization_content").insert(payload);if(r.error)return setStatus(r.error.message);setStatus(editingContent?"Information updated.":"Information added.");setContent(blankContent());setDocFile(null);setEditingContent(null);load()}
 async function uploadMedia(e:React.FormEvent){e.preventDefault();if(!client){setStatus("Supabase is not configured.");return;}if(!media)return setStatus("Choose an image or video.");setStatus("Uploading media…");const type=media.type.startsWith("video/")?"video":"image";const path=`${Date.now()}-${media.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const up=await client.storage.from("project-gallery").upload(path,media,{upsert:true});if(up.error)return setStatus(up.error.message);const url=client.storage.from("project-gallery").getPublicUrl(path).data.publicUrl;const r=await client.from("gallery_items").insert({title:mediaTitle||null,description:mediaDescription||null,media_type:type,media_url:url,published:true});if(r.error)return setStatus(r.error.message);setMedia(null);setMediaTitle("");setMediaDescription("");setStatus("Gallery item added.");load()}
 async function toggle(table:string,id:string,current:boolean){if(!client){setStatus("Supabase is not configured.");return;}const r=await client.from(table).update({published:!current}).eq("id",id);if(r.error)setStatus(r.error.message);else load()}
 async function remove(table:string,id:string){if(!client){setStatus("Supabase is not configured.");return;}if(!confirm("Delete this item permanently?"))return;const r=await client.from(table).delete().eq("id",id);if(r.error)setStatus(r.error.message);else{setStatus("Item deleted.");load()}}
 if(!session)return <main className="min-h-screen bg-paper p-8 pt-32"><div className="max-w-md mx-auto bg-white rounded-2xl border border-[#e5dfd1] p-8"><span className="eyebrow">Administration</span><h1 className="font-display text-3xl font-bold mt-3">Daraja Content Dashboard</h1><p className="text-ink/60 text-sm mt-2">Manage organizational content securely.</p><form onSubmit={signIn} className="mt-7 space-y-4"><input className="w-full border rounded-lg p-3" type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input className="w-full border rounded-lg p-3" type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="w-full rounded-full bg-ink text-paper py-3 font-mono text-xs uppercase tracking-widest">Sign In</button></form><p className="text-sm mt-4 text-ink/60">{status}</p></div></main>;
 return <main className="min-h-screen bg-paper p-6 md:p-10 pt-28"><div className="max-w-[1200px] mx-auto"><div className="flex justify-between items-center gap-4 mb-8"><div><span className="eyebrow">Administration</span><h1 className="font-display font-bold text-3xl md:text-4xl mt-2">Daraja Content Dashboard</h1><p className="text-ink/60 mt-2">Manage the public organization website without editing code.</p></div><div className="flex gap-3"><Link href="/" className="rounded-full border border-ink px-4 py-2 font-mono text-xs">Website</Link><button onClick={()=>client?.auth.signOut()} className="rounded-full bg-ink text-paper px-4 py-2 font-mono text-xs">Sign out</button></div></div><p className="mb-7 text-ink/60">{status}</p>
 <div className="grid lg:grid-cols-3 gap-6"><form onSubmit={saveLeader} className="bg-white rounded-2xl border border-[#e5dfd1] p-7 space-y-4"><span className="eyebrow">Leadership</span><h2 className="font-display font-bold text-2xl">{editingLeader?"Edit leader":"Add leader"}</h2><input className="w-full border rounded-lg p-3" placeholder="Full name" value={leader.name} onChange={e=>setLeader({...leader,name:e.target.value})} required/><input className="w-full border rounded-lg p-3" placeholder="Position / role" value={leader.role} onChange={e=>setLeader({...leader,role:e.target.value})} required/><textarea className="w-full border rounded-lg p-3" placeholder="Biography" rows={5} value={leader.bio} onChange={e=>setLeader({...leader,bio:e.target.value})}/><input className="w-full border rounded-lg p-3" type="number" placeholder="Display order" value={leader.sort_order} onChange={e=>setLeader({...leader,sort_order:Number(e.target.value)})}/><input type="file" accept="image/*" onChange={e=>setLeaderFile(e.target.files?.[0]||null)}/><label className="text-sm"><input type="checkbox" checked={leader.published} onChange={e=>setLeader({...leader,published:e.target.checked})}/> Published</label><button className="rounded-full bg-ink text-paper px-6 py-3 font-mono text-xs uppercase tracking-widest">{editingLeader?"Update Leader":"Add Leader"}</button>{editingLeader&&<button type="button" className="ml-2 rounded-full border px-6 py-3 font-mono text-xs" onClick={()=>{setLeader(blankLeader());setEditingLeader(null)}}>Cancel</button>}</form>
 <form onSubmit={saveContent} className="bg-white rounded-2xl border border-[#e5dfd1] p-7 space-y-4"><span className="eyebrow">Organization & Impact</span><h2 className="font-display font-bold text-2xl">{editingContent?"Edit information":"Add information"}</h2><select className="w-full border rounded-lg p-3" value={content.section} onChange={e=>setContent({...content,section:e.target.value})}><option value="identity">Mission / Vision / History</option><option value="impact">Impact / Results</option><option value="governance">Governance</option><option value="safeguarding">Safeguarding</option><option value="accountability">Reports / Policies / Transparency</option></select><input className="w-full border rounded-lg p-3" placeholder="Title" value={content.title} onChange={e=>setContent({...content,title:e.target.value})} required/><textarea className="w-full border rounded-lg p-3" placeholder="Information" rows={5} value={content.body} onChange={e=>setContent({...content,body:e.target.value})}/><input className="w-full border rounded-lg p-3" placeholder="Metric value (optional)" value={content.metric_value} onChange={e=>setContent({...content,metric_value:e.target.value})}/><input className="w-full border rounded-lg p-3" placeholder="Metric label (optional)" value={content.metric_label} onChange={e=>setContent({...content,metric_label:e.target.value})}/><input type="file" accept=".pdf,.doc,.docx" onChange={e=>setDocFile(e.target.files?.[0]||null)}/><label className="text-sm"><input type="checkbox" checked={content.published} onChange={e=>setContent({...content,published:e.target.checked})}/> Published</label><button className="rounded-full bg-ink text-paper px-6 py-3 font-mono text-xs uppercase tracking-widest">{editingContent?"Update":"Publish"}</button>{editingContent&&<button type="button" className="ml-2 rounded-full border px-6 py-3 font-mono text-xs" onClick={()=>{setContent(blankContent());setEditingContent(null)}}>Cancel</button>}</form>
 <form onSubmit={uploadMedia} className="bg-white rounded-2xl border border-[#e5dfd1] p-7 space-y-4"><span className="eyebrow">Gallery</span><h2 className="font-display font-bold text-2xl">Upload media</h2><input className="w-full border rounded-lg p-3" placeholder="Title" value={mediaTitle} onChange={e=>setMediaTitle(e.target.value)}/><textarea className="w-full border rounded-lg p-3" placeholder="Description" rows={5} value={mediaDescription} onChange={e=>setMediaDescription(e.target.value)}/><input type="file" accept="image/*,video/*" onChange={e=>setMedia(e.target.files?.[0]||null)} required/><button className="rounded-full bg-ink text-paper px-6 py-3 font-mono text-xs uppercase tracking-widest">Upload to Gallery</button></form></div>
 <section className="mt-7 bg-white rounded-2xl border border-[#e5dfd1] p-7"><h2 className="font-display font-bold text-2xl mb-5">Leadership records</h2>{leaders.map(x=><div key={x.id} className="flex flex-col md:flex-row gap-4 items-start border-t py-5"><img src={x.photo_url} alt="" className="w-20 h-20 object-cover rounded-xl"/><div className="flex-1"><strong>{x.name}</strong><div className="text-sm text-ink/60">{x.role} · {x.published?"Published":"Hidden"}</div><p className="text-sm mt-2">{x.bio}</p></div><div className="flex gap-2 flex-wrap"><button onClick={()=>{setEditingLeader(x.id||null);setLeader({...x,bio:x.bio||""})}} className="border rounded-full px-3 py-2 text-xs">Edit</button><button onClick={()=>toggle("organization_leaders",x.id||"",x.published)} className="border rounded-full px-3 py-2 text-xs">{x.published?"Hide":"Publish"}</button><button onClick={()=>remove("organization_leaders",x.id||"")} className="border rounded-full px-3 py-2 text-xs">Delete</button></div></div>)}</section>
 <section className="mt-7 bg-white rounded-2xl border border-[#e5dfd1] p-7"><h2 className="font-display font-bold text-2xl mb-5">Organization & impact records</h2>{contents.map(x=><div key={x.id} className="border-t py-5 flex flex-col md:flex-row gap-4"><div className="flex-1"><div className="text-xs uppercase tracking-widest text-ink/50">{x.section} · {x.published?"Published":"Hidden"}</div><strong>{x.title}</strong>{x.metric_value&&<div className="font-display text-xl mt-1">{x.metric_value} <span className="text-sm font-body">{x.metric_label}</span></div>}<p className="text-sm mt-2">{x.body}</p>{x.document_url&&<a className="underline text-sm" href={x.document_url} target="_blank" rel="noreferrer">{x.document_name||"Open document"}</a>}</div><div className="flex gap-2 flex-wrap"><button onClick={()=>{setEditingContent(x.id||null);setContent({...x,body:x.body||"",metric_value:x.metric_value||"",metric_label:x.metric_label||"",document_url:x.document_url||"",document_name:x.document_name||""})}} className="border rounded-full px-3 py-2 text-xs">Edit</button><button onClick={()=>toggle("organization_content",x.id||"",x.published)} className="border rounded-full px-3 py-2 text-xs">{x.published?"Hide":"Publish"}</button><button onClick={()=>remove("organization_content",x.id||"")} className="border rounded-full px-3 py-2 text-xs">Delete</button></div></div>)}</section>
 <section className="mt-7 bg-white rounded-2xl border border-[#e5dfd1] p-7"><h2 className="font-display font-bold text-2xl mb-5">Gallery records</h2>{gallery.map(x=><div key={x.id} className="border-t py-5 flex justify-between gap-4"><div><strong>{x.title||"Untitled media"}</strong><div className="text-sm text-ink/60">{x.media_type} · {x.published?"Published":"Hidden"}</div><p className="text-sm mt-2">{x.description}</p></div><div className="flex gap-2"><button onClick={()=>toggle("gallery_items",x.id,x.published)} className="border rounded-full px-3 py-2 text-xs">{x.published?"Hide":"Publish"}</button><button onClick={()=>remove("gallery_items",x.id)} className="border rounded-full px-3 py-2 text-xs">Delete</button></div></div>)}</section>
 </div></main>
}
