"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabaseClient";

export default function AdminPage(){
 const [session,setSession]=useState<any>(null); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [status,setStatus]=useState(""); const [title,setTitle]=useState(""); const [description,setDescription]=useState(""); const [proposal,setProposal]=useState<File|null>(null); const [media,setMedia]=useState<File|null>(null); const [mediaTitle,setMediaTitle]=useState(""); const [mediaDescription,setMediaDescription]=useState("");
 const client=supabase;
 useEffect(()=>{if(!client)return;client.auth.getSession().then(({data})=>setSession(data.session));const {data}=client.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[client]);
 async function signIn(e:React.FormEvent){e.preventDefault();if(!client)return;setStatus("Signing in…");const {data,error}=await client.auth.signInWithPassword({email,password});if(error)setStatus(error.message);else{setSession(data.session);setStatus("Signed in.")}}
 async function uploadProposal(e:React.FormEvent){e.preventDefault();if(!client||!proposal)return;setStatus("Uploading proposal…");const path=`${Date.now()}-${proposal.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const up=await client.storage.from("project-proposals").upload(path,proposal);if(up.error){setStatus(up.error.message);return}const {data}=client.storage.from("project-proposals").getPublicUrl(path);const ins=await client.from("project_proposals").insert({title,description,file_url:data.publicUrl,file_name:proposal.name,published:true});setStatus(ins.error?ins.error.message:"Proposal published successfully.");if(!ins.error){setTitle("");setDescription("");setProposal(null)}}
 async function uploadMedia(e:React.FormEvent){e.preventDefault();if(!client||!media)return;setStatus("Uploading media…");const type=media.type.startsWith("video/")?"video":"image";const path=`${Date.now()}-${media.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const up=await client.storage.from("project-gallery").upload(path,media);if(up.error){setStatus(up.error.message);return}const {data}=client.storage.from("project-gallery").getPublicUrl(path);const ins=await client.from("gallery_items").insert({title:mediaTitle||null,description:mediaDescription||null,media_type:type,media_url:data.publicUrl,published:true});setStatus(ins.error?ins.error.message:"Gallery item published successfully.");if(!ins.error){setMediaTitle("");setMediaDescription("");setMedia(null)}}
 if(!client)return <main className="min-h-screen bg-paper p-8 pt-32"><div className="max-w-xl mx-auto"><h1 className="font-display text-3xl font-bold">Admin unavailable</h1><p className="mt-3 text-ink/65">Add the Supabase environment variables in Vercel before using the dashboard.</p></div></main>;
 if(!session)return <main className="min-h-screen bg-paper p-8 pt-32"><div className="max-w-md mx-auto bg-white rounded-2xl border border-[#e5dfd1] p-8"><span className="eyebrow">Administration</span><h1 className="font-display text-3xl font-bold mt-3">Content Dashboard</h1><p className="text-ink/60 text-sm mt-2">Sign in with the Supabase administrator account.</p><form onSubmit={signIn} className="mt-7 space-y-4"><input className="w-full border rounded-lg p-3" type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input className="w-full border rounded-lg p-3" type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="w-full rounded-full bg-ink text-paper py-3 font-mono text-xs uppercase tracking-widest">Sign In</button></form><p className="text-sm mt-4 text-ink/60">{status}</p></div></main>;
 return <main className="min-h-screen bg-paper p-6 md:p-10 pt-28"><div className="max-w-[1100px] mx-auto"><div className="flex justify-between items-center gap-4 mb-10"><div><span className="eyebrow">Administration</span><h1 className="font-display font-bold text-3xl md:text-4xl mt-2">Content Dashboard</h1></div><div className="flex gap-3"><Link href="/" className="rounded-full border border-ink px-4 py-2 font-mono text-xs">Website</Link><button onClick={()=>client.auth.signOut()} className="rounded-full bg-ink text-paper px-4 py-2 font-mono text-xs">Sign out</button></div></div><p className="mb-7 text-ink/60">{status}</p><div className="grid lg:grid-cols-2 gap-7"><form onSubmit={uploadProposal} className="bg-white rounded-2xl border border-[#e5dfd1] p-7 space-y-4"><span className="eyebrow">Project Proposals</span><h2 className="font-display font-bold text-2xl">Upload a proposal</h2><input className="w-full border rounded-lg p-3" placeholder="Project title" value={title} onChange={e=>setTitle(e.target.value)} required/><textarea className="w-full border rounded-lg p-3" placeholder="Description" rows={4} value={description} onChange={e=>setDescription(e.target.value)}/><input type="file" accept=".pdf,.doc,.docx" onChange={e=>setProposal(e.target.files?.[0]||null)} required/><button className="rounded-full bg-ink text-paper px-6 py-3 font-mono text-xs uppercase tracking-widest">Publish Proposal</button></form><form onSubmit={uploadMedia} className="bg-white rounded-2xl border border-[#e5dfd1] p-7 space-y-4"><span className="eyebrow">Gallery</span><h2 className="font-display font-bold text-2xl">Upload photo or video</h2><input className="w-full border rounded-lg p-3" placeholder="Title" value={mediaTitle} onChange={e=>setMediaTitle(e.target.value)}/><textarea className="w-full border rounded-lg p-3" placeholder="Description" rows={4} value={mediaDescription} onChange={e=>setMediaDescription(e.target.value)}/><input type="file" accept="image/*,video/*" onChange={e=>setMedia(e.target.files?.[0]||null)} required/><button className="rounded-full bg-ink text-paper px-6 py-3 font-mono text-xs uppercase tracking-widest">Publish Media</button></form></div></div></main>
}
