"use client";
import {useEffect,useState} from "react";
import {supabase} from "@/lib/supabaseClient";
type Program={id:string;title:string};
type Media={id:string;title:string;description:string|null;media_url:string;media_type:string;published:boolean;program_id:string|null};
export default function ProgramMediaManager(){
 const [programs,setPrograms]=useState<Program[]>([]),[items,setItems]=useState<Media[]>([]),[programId,setProgramId]=useState(""),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[file,setFile]=useState<File|null>(null),[published,setPublished]=useState(true),[msg,setMsg]=useState("");
 async function load(){const c=supabase;if(!c)return;const [p,m]=await Promise.all([c.from("organization_programs").select("id,title").order("sort_order"),c.from("gallery_items").select("*").not("program_id","is",null).order("created_at",{ascending:false})]);if(p.error)setMsg(p.error.message);else setPrograms(p.data||[]);if(m.error)setMsg(m.error.message);else setItems(m.data||[])}
 useEffect(()=>{load()},[]);
 async function add(e:React.FormEvent){e.preventDefault();const c=supabase;if(!c){setMsg("Supabase is not configured.");return}if(!programId||!file){setMsg("Select a program and a photo or video.");return}setMsg("Uploading...");const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${Date.now()}-${safe}`;const up=await c.storage.from("gallery-media").upload(path,file,{upsert:true});if(up.error){setMsg(up.error.message);return}const url=c.storage.from("gallery-media").getPublicUrl(path).data.publicUrl;const type=file.type.startsWith("video/")?"video":"image";const r=await c.from("gallery_items").insert({title,description,media_url:url,media_type:type,program_id:programId,published});if(r.error){setMsg(r.error.message);return}setTitle("");setDescription("");setFile(null);setMsg("Media published to the selected program.");load()}
 async function toggle(x:Media){const c=supabase;if(!c)return;const r=await c.from("gallery_items").update({published:!x.published}).eq("id",x.id);if(r.error)setMsg(r.error.message);else load()}
 async function remove(x:Media){const c=supabase;if(!c||!confirm("Delete this media item?"))return;const r=await c.from("gallery_items").delete().eq("id",x.id);if(r.error)setMsg(r.error.message);else load()}
 return <section className="admin-card"><div><span className="eyebrow">PROGRAM MEDIA</span><h2>Photos & videos from the field</h2><p>Attach each story image or video to the programme it documents.</p></div>{msg&&<p className="notice">{msg}</p>}<form className="admin-form" onSubmit={add}><select required value={programId} onChange={e=>setProgramId(e.target.value)}><option value="">Select programme</option>{programs.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select><input placeholder="Media title / caption" value={title} onChange={e=>setTitle(e.target.value)}/><textarea placeholder="Short description (optional)" value={description} onChange={e=>setDescription(e.target.value)}/><label>Photo or video<input required type="file" accept="image/*,video/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label><input type="checkbox" checked={published} onChange={e=>setPublished(e.target.checked)}/> Publish immediately</label><button className="button" type="submit">Upload & Publish</button></form><div className="admin-list">{items.map(x=><div className="admin-row" key={x.id}><div><small>{x.published?"Published":"Hidden"} · {x.media_type}</small><strong>{x.title||"Untitled media"}</strong><p>{programs.find(p=>p.id===x.program_id)?.title||"Programme"}</p></div><div><button onClick={()=>toggle(x)}>{x.published?"Hide":"Publish"}</button><button onClick={()=>remove(x)}>Delete</button></div></div>)}</div></section>}
