"use client";
import {useEffect,useState} from "react";
import {supabase} from "@/lib/supabaseClient";

type Program={id?:string;title:string;summary:string;description:string;objective:string;target_community:string;location:string;activities:string;impact:string;image_url:string;document_url:string;document_name:string;sort_order:number;published:boolean};
const blank=():Program=>({title:"",summary:"",description:"",objective:"",target_community:"",location:"",activities:"",impact:"",image_url:"",document_url:"",document_name:"",sort_order:0,published:true});
export default function ProgramsAdmin(){const[s,setS]=useState<any>(null),[items,setItems]=useState<Program[]>([]),[form,setForm]=useState(blank()),[editing,setEditing]=useState<string|null>(null),[image,setImage]=useState<File|null>(null),[doc,setDoc]=useState<File|null>(null),[msg,setMsg]=useState("");
useEffect(()=>{supabase.auth.getSession().then(({data})=>setS(data.session));const{x}=supabase.auth.onAuthStateChange((_e,ss)=>setS(ss));return()=>x.subscription.unsubscribe()},[]);useEffect(()=>{if(s)load()},[s]);async function load(){const{data,error}=await supabase.from("organization_programs").select("*").order("sort_order");if(error)setMsg(error.message);setItems(data||[])}
async function save(e:React.FormEvent){e.preventDefault();let p={...form};if(image){const path=`${Date.now()}-${image.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const u=await supabase.storage.from("program-media").upload(path,image,{upsert:true});if(u.error)return setMsg(u.error.message);p.image_url=supabase.storage.from("program-media").getPublicUrl(path).data.publicUrl}if(doc){const path=`${Date.now()}-${doc.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const u=await supabase.storage.from("program-documents").upload(path,doc,{upsert:true});if(u.error)return setMsg(u.error.message);p.document_url=supabase.storage.from("program-documents").getPublicUrl(path).data.publicUrl;p.document_name=doc.name}const r=editing?await supabase.from("organization_programs").update(p).eq("id",editing):await supabase.from("organization_programs").insert(p);if(r.error)return setMsg(r.error.message);setMsg(editing?"Program updated.":"Program published.");setForm(blank());setEditing(null);setImage(null);setDoc(null);load()}
async function del(id:string){if(!confirm("Delete this program?"))return;const r=await supabase.from("organization_programs").delete().eq("id",id);if(r.error)setMsg(r.error.message);else load()}async function toggle(x:Program){const r=await supabase.from("organization_programs").update({published:!x.published}).eq("id",x.id);if(r.error)setMsg(r.error.message);else load()}
if(!s)return <main className="admin-page"><div className="admin-card"><h1>Program Administration</h1><p>Sign in through the main admin dashboard first.</p><a className="button" href="/admin">Open Admin Login</a></div></main>;
return <main className="admin-page"><div className="admin-head"><div><span className="eyebrow">PROGRAMS CMS</span><h1>Programs we conduct</h1><p>Manage current programs and the information donors can review.</p></div><a className="button button-light" href="/admin">← Main Dashboard</a></div>{msg&&<p className="notice">{msg}</p>}<div className="admin-grid"><form className="admin-card admin-form" onSubmit={save}><h2>{editing?"Edit Program":"Add Program"}</h2><input required placeholder="Program title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input placeholder="Short summary" value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/><textarea placeholder="Full description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input placeholder="Objective" value={form.objective} onChange={e=>setForm({...form,objective:e.target.value})}/><input placeholder="Target community / beneficiaries" value={form.target_community} onChange={e=>setForm({...form,target_community:e.target.value})}/><input placeholder="Location" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/><textarea placeholder="Key activities" value={form.activities} onChange={e=>setForm({...form,activities:e.target.value})}/><textarea placeholder="Impact / results" value={form.impact} onChange={e=>setForm({...form,impact:e.target.value})}/><input type="number" placeholder="Display order" value={form.sort_order} onChange={e=>setForm({...form,sort_order:+e.target.value})}/><label>Program image<input type="file" accept="image/*" onChange={e=>setImage(e.target.files?.[0]||null)}/></label><label>Program document<input type="file" accept=".pdf,.doc,.docx" onChange={e=>setDoc(e.target.files?.[0]||null)}/></label><label><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/> Published</label><button className="button" type="submit">{editing?"Update Program":"Publish Program"}</button>{editing&&<button className="button button-light" type="button" onClick={()=>{setForm(blank());setEditing(null)}}>Cancel</button>}</form><section className="admin-card admin-list"><h2>Current programs</h2>{items.length===0?<p>No programs added yet.</p>:items.map(x=><div className="admin-row" key={x.id}><div><small>{x.published?"Published":"Hidden"} · {x.location||"Location not set"}</small><strong>{x.title}</strong><p>{x.summary||x.description}</p></div><div><button onClick={()=>{setForm(x);setEditing(x.id||null)}}>Edit</button><button onClick={()=>toggle(x)}>{x.published?"Hide":"Publish"}</button><button onClick={()=>del(x.id||"")}>Delete</button></div></div>)}</section></div></main>}
